### ISSUE TITLE
Visible Error States

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#106]
We should at least hide information from query like wpdb prefix

https://github.com/palasthotel/grid-wordpress/blob/master/wordpress_plugin.php#L440

**Comment by greatestview** [comment]
+1 Currently the full SQL query including table names is visible in the frontend, when SQL connection fails.

**Comment by EdwardBock** [comment]
With version 1.7.6 query details goes to error log only.
