### ISSUE TITLE
Set error-status-codes for mysql-errors

### ISSUE THREAD

**Issue by JuliaKrischik** [palasthotel/grid-wordpress#107]
Hi @EdwardBock,

I recently had a Problem with [this Line](https://github.com/palasthotel/grid-wordpress/blob/master/wordpress_plugin.php#L440).

I needed to know if a request failed because of mysql-timeouts, but grid just dies here. So I changed it to this, to have the error-code available:

`````
if ( $die ) {
		$result = $grid_connection->query( $querystring );
		if($result === false){
			http_response_code (500);
			die( $querystring.' failed: '.$grid_connection->error );
		}
	}
`````
Would you please change this in the official plugin too?

**Comment by EdwardBock** [comment]
Thanks @JuliaKrischik 

Related to #106

**Comment by EdwardBock** [comment]
With version 1.7.6 query details goes to error log only.
