### ISSUE TITLE
1.7.11 breaks teaser templates

### ISSUE THREAD

**Issue by poetaster** [palasthotel/grid-wordpress#114]
see also: https://wordpress.org/support/topic/1-7-11-breaks-teaser-templates/

The default:
<?php the_excerpt(); ?>

within a have_posts loop, produces empty out.

Reverting to old grid, the templates work as expected.

**Comment by poetaster** [comment]
I'm reporting for netzpolitik.org. This development and the last bug I submitted break PH's templates, made for netzpolitik.org ... We're willing to pay to get this sped up since our caching system is now no longer that which it has been (first static rendering, then via proxy & varnish) since relaunch. And, we can't update the plugin without breaking the site.

**Comment by EdwardBock** [comment]
@poetaster 

Please try to install version 1.7.12 . Problems should be fixed.

https://github.com/palasthotel/grid-wordpress/commit/7fa325d43f5532ddad3622f70fd2a871d9190703
