### ISSUE TITLE
Excerpts are missing

### ISSUE THREAD

**Issue by davviau** [palasthotel/grid-wordpress#115]
After updating excerpts are no longer being displayed on my client's site www.lostandlovingit.com.au It isn't the Grid plugin that isn't showing the excerpts it's other plugins. They were displaying fine until I updated the Grid plugin.

**Comment by EdwardBock** [comment]
Hi @davviau 

thanks for you report. Please install the version 1.7.12 which should available at wordpress.org in a few minutes.

Fix: 
https://github.com/palasthotel/grid-wordpress/commit/7fa325d43f5532ddad3622f70fd2a871d9190703
