### ISSUE TITLE
Grid Style slugs text length

### ISSUE THREAD

**Issue by kroppenstedt** [palasthotel/grid-wordpress#120]
* Better UI/UX  needed
* Text length limitation for slug needed?

**Comment by EdwardBock** [comment]
With update 1.8.4 slug length will be max of 190 varchar (needed because of unique key index) but Style can be set free.

https://github.com/palasthotel/grid/commit/1b1c4291e579779606424f92c54eee4891e42191

**Comment by EdwardBock** [comment]
Slug input is limited to its max char length of 190
