### ISSUE TITLE
Post Box: Placing of pages not possible

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid-wordpress#123]
Tested on Grid v1.8.0

You can choose pages via »Single Contents« autocomplete search field and place the post box in grid, but the object passed to the frondend is incomplete: `$this->output` and `$this->publish` are empty strings. That’s probably because the post box uses `get_post` for retrieving pages instead of `get_pages`: https://github.com/palasthotel/grid-wordpress/blob/master/core/classes/wordpress/grid_post_box.php#L41

Changing backend settings in Grid makes no difference as far as I can tell.

Could you have a look into this @EdwardBock? Thank you :)

**Comment by EdwardBock** [comment]
@greatestview I checked on this. get_post is not having any problems with post ids of pages. Have a look at https://doc.grid.ws . On the homepage we have to pages placed with post box. Working fine.

**Comment by greatestview** [comment]
That’s true, it had something to do with a custom post box override. Thank you!
