### ISSUE TITLE
Fatal after Update on Domainfactory Server 110227 Digitalkombinat

### ISSUE THREAD

**Issue by MarcusAbel** [palasthotel/grid-wordpress#126]
<b>Fatal error</b>:  Uncaught Error: Class name must be a valid object or a string in .../wp-content/plugins/grid/lib/grid/components/grid_box.php:42

**Comment by MarcusAbel** [comment]
This error was shown after updateing wordpress of sg-gutersloh.de from 1.8.? to neweset version 2.???

**Comment by EdwardBock** [comment]
What I expected. There were custom boxes that had a constructor with no parent call. Is fixed and updated.
