### ISSUE TITLE
Problems with SEO plugin (from Yoast) 

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#20]
Moved from grid lib because it's a wordpress spezific problem:

> Hey @mkernel,
> 
> WordPress runs two times through the boxes with enabled SEO plugin (from Yoast) before the final rendering. So we get an unwanted offset of 2 - is there a workaround to prevent this?

https://github.com/palasthotel/grid/issues/309

**Comment by mkernel** [comment]
Seems to be solved by the yoast team.
