### ISSUE TITLE
SQL injection vulnerability

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#24]
@mkernel What do you think?
From "danielfriesen" on Wordpress.org

```
User data like $_GET['postid'] shouldn't be concatenated directly into SQL like it is in grid_wp_thegrid.

Bad practice like this means that there's a fair chance that there is a SQL injection vulnerability somewhere in this plugin.
```

https://wordpress.org/support/topic/sql-concatenation-bad-practice

**Comment by mkernel** [comment]
We should fix that. He's right. Will have a look next week.

**Comment by EdwardBock** [comment]
@mkernel could you have a look at this today?

**Comment by mkernel** [comment]
It's fixed. and committed.

**Comment by EdwardBock** [comment]
https://wordpress.org/support/topic/sql-concatenation-bad-practice

**Comment by EdwardBock** [comment]
Nice!
