### ISSUE TITLE
Facebook and Twitter Plugin in Plugin

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#25]
From "danielfreisen" on Wordpress.org

```
The Grid Facebook like box and Grid Twitterbox embedded in the Grid plugin show up as separate plugins in the plugin list.

WordPress takes the current version from each php file but the latest version from the version of Grid on the plugins site. Since the two extra plugins are version 0.0 and the latest version of Grid is 1.1 this means that the WordPress updates page persistently states that Grid Facebook like box and Grid Twitterbox have updates and letting it updates just re-downloads the exact same version of Grid again.
```

https://wordpress.org/support/topic/grid-facebook-like-box-and-twitterbox-persist-in-updates

@mkernel I think I could simply equalize the version numbers of all Plugins, right?

**Comment by EdwardBock** [comment]
Or do we even need those boxes to be separate plugins anymore, now that we have the box trash?

**Comment by mkernel** [comment]
The embedded plugins are already equal in version to fix the problem. I think it's better to keep them separate plugins as they add some libraries not every project needs.

We could extract them to completely separate projects, but I don't see a reason for it. 
As said: the problem no longer persists as we have equalized the version numbers already.
