### ISSUE TITLE
Add Grid as submodule

### ISSUE THREAD

**Issue by barooney** [palasthotel/grid-wordpress#27]
You state in the documentation, that this repository alone is not functional, you'll have to manually add the grid repository into the 'lib' folder. Define grid as a submodule, which will be cloned into 'lib'.
By doing this, all developers are ready to go, when they clone this repository.

**Comment by EdwardBock** [comment]
@mkernel @benthebear 
We talked about that. I forgot the result of our discussion. Did we have any arguments against that or did we just didn't do it yet?

**Comment by EdwardBock** [comment]
@benthebear 
Next time you are in the office, we should discuss this, please.

**Comment by benthebear** [comment]
@EdwardBock @mkernel I am in Office now. Discussion anyone?

**Comment by benthebear** [comment]
@barooney  We discussed it here and came to the conclusion, that we don't want to use submodules in this case. Judging from our experience, a Submodule just relocates the work, and makes it a bit more complex: The way we work now, you "only" have to install the lib once. Buuut when having a submodule you have to add commit within the Submodul AND again within the Main Module … that lead to quite a few problems, when we tried that. Sooo sorry, no, we won't do that.
Are you okay with that?

**Comment by barooney** [comment]
Actually, that's why I opened the issue in the first place:

The workflow you describe did not work. I downloaded the master from this repo and from the base grid repo and they didn't play well together. One repository became incompatible towards the other. Having a submodule defined could solve this problem, so even if you push the master, the version would stay compatible.

In the best case you would update this and the other repo at the same time and push tags with it.
I'm pretty sure you could configure git to work like this.

**Comment by mkernel** [comment]
incompatibilities can happen between releases of library and plugin - that's kind of expectable on a development branch. The HEADs on both repositories are not for public use - they tend to break from time to time.

Therefore if you need "stable" stuff: use either the corresponding wordpress tags or the code available on wordpress.org.

If you pull the wordpress and library from the corrseponding master's and they break: simply pull again a few hours later. Normally we fix incompatibilities between both repositories within hours. And it's a very rare case.
