### ISSUE TITLE
No boxes for Landing Pages or Sidebars

### ISSUE THREAD

**Issue by barooney** [palasthotel/grid-wordpress#29]
I have installed Grid on a fresh install of WordPress 4.1 de-DE. There are no other plugins activated.
The three plugins, which come bundled with The Grid are all enabled (The Grid itself, the Facebook Like box and the Twitterbox). Nonetheless, there is no box shown on the Landing Page 'builder' or Sidebar 'builder' (see screenshots below). I have verified that it's not a CSS bug, which pushes the list away, it is dead-end empty.

After completely removing and adding The Grid again, the problem still persists with the current master branch.

Is there a fix or am I missing something?

Additional information:

Apache Version:
```
$ apache2 -v
Server version: Apache/2.4.10 (Ubuntu)
Server built:   Jul 22 2014 22:57:50
```

PHP-Version
```
$ php -v
PHP 5.5.17-2+deb.sury.org~precise+1 (cli) (built: Sep 25 2014 09:07:54)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
```

MySQL Server Version:
```
$ mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1724
Server version: 5.5.38-0ubuntu0.12.04.1 (Ubuntu)
```

![bildschirmfoto 2015-01-08 um 14 16 42](https://cloud.githubusercontent.com/assets/7101151/5663026/87f90fa6-9741-11e4-8aae-01d095fa44f5.png)
![bildschirmfoto 2015-01-08 um 14 21 04](https://cloud.githubusercontent.com/assets/7101151/5663028/9e2cdfdc-9741-11e4-8b49-e6c0ed282f24.png)

**Comment by mkernel** [comment]
@barooney did you clone the repository or did you fetch the official grid release?
Furthermore: please have a look at the debugger console of your browser for a hint. You can also enable grid debugging in the grid settings. That may also help.

**Comment by barooney** [comment]
It's the master branch, as stated above. It throws the following error in the developer console:

```
 <br />
<b>Warning</b>:  Missing argument 1 for grid_error_box::__construct(), called in /var/www/public/wp-content/plugins/grid/lib/classes/grid_db.php on line 1201 and defined in <b>/var/www/public/wp-content/plugins/grid/lib/classes/grid_error_box.php</b> on line <b>18</b><br />
{"result":[{"type":"static","title":"Static content","criteria":[]},{"type":"abstract_list","title":"Lists","criteria":[]},{"type":"reference","title":"Reusable boxes","criteria":[]},{"type":"post","title":"Contents","criteria":["title"]}]}
```

I removed both repositories and opted to install the wordpress-1.1 tagged release of both versions. This worked.

**Comment by mkernel** [comment]
So thats an issue for @EdwardBock

**Comment by EdwardBock** [comment]
On it!

**Comment by EdwardBock** [comment]
@mkernel @barooney 
The grid_error_box has a constructor argument for it's error message. That's now optional because the getMetaTypes function in grid_db.php needs it like so!
