### ISSUE TITLE
templates path in post_content box

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#41]
@mkernel 
post_content Box uses a manual implementation of templats path. We should use the hew hierachical templating mechanism for that.

**Comment by EdwardBock** [comment]
@mkernel 
Please have a look at this Problem next Grid Day so we have a clean and capsuled templating mechanism

**Comment by mkernel** [comment]
I rewrote it to use the templatePaths array, however we should refactor all this rendering stuff to be more versatile. Anyway: have a look.

**Comment by EdwardBock** [comment]
Its ok how it is for now. We should refactor this when we are done with refactoring the templating engine in grid lib: https://github.com/palasthotel/grid/issues/371
