### ISSUE TITLE
parseerror when deleting a box

### ISSUE THREAD

**Issue by barooney** [palasthotel/grid-wordpress#51]
I want to delete a box by clicking on the "delete" flag on the box. The box soon disappears, but the following error message pops up:

```
Method: removeBox
Status: (200) -> parsererror
ResponseText: 

Fatal error:  Call to a member function delete() on a non-object in /var/www/docroot/wp-content/plugins/grid/lib/classes/grid_ajaxendpoint.php on line 279
```

This happens when using Grid version 1.3.3. The box is removed correctly from the Grid, though.

![bildschirmfoto 2015-04-08 um 11 42 28](https://cloud.githubusercontent.com/assets/7101151/7042736/5f654df4-dde4-11e4-9c69-b88a6a06651b.png)

**Comment by EdwardBock** [comment]
Should not happen anymore. See: Grid library fix one operation at a time
