### ISSUE TITLE
Deleting reusable boxes

### ISSUE THREAD

**Issue by barooney** [palasthotel/grid-wordpress#55]
I'm wondering how to delete reusable grid boxes.

I am pretty sure it is not used in an existing grid, so there should not be any broken references.

**Comment by mkernel** [comment]
If there's no delete button present it's placed somewhere. What's easy to overlook: if the box _was_ placed in a revision of a grid, there's a reference holding it. Deleting revisions is not possible - so in that case you can either delete the whole grid to break the reference or use one of our trash modules to hide the reusable box.

**Comment by EdwardBock** [comment]
@barooney @mkernel 
I just requested an wordpress.org SVN for the grid trash plugin.

I think we can close this issue now.
