### ISSUE TITLE
Nested lists

### ISSUE THREAD

**Issue by barooney** [palasthotel/grid-wordpress#57]
I'm trying to setup a grid box, which should render multiple slides in a slideshow.

Within the slideshow, there should be a background image and multiple labels.
these labels can vary and it's not sure to have a fixed number of labels.

Therefore, I tried to create a nested list like this:

```
public function contentStructure() {
	return array(
		array(
			'key'   => 'slides', 
			'label' => 'Slides',
			'type'  => 'list',
			'contentstructure' => array(
				array(
					'key' => 'background',
					'label' => 'Background',
					'type' => 'wp-mediaselect',
				),
				array(
					'key'   => 'labels',
					'label' => 'Labels',
					'type'  => 'list',
					'contentStructure' => array(
						array(
							'key' => 'text',
							'label' => 'Text',
							'type' => 'text',
						)
					)
				)
			)
		),
	);
}
```

The result shown in the grid is the following:

It adds a new field, but the ```text``` field in it is not rendered:

![bildschirmfoto 2015-07-04 um 20 24 14](https://cloud.githubusercontent.com/assets/7101151/8509008/c4d4c21a-228a-11e5-9253-f9ea43520ea6.png)

**Comment by EdwardBock** [comment]
@barooney 
That was a problem with wp-mediaselect JavaScript in the grid library. Was fixed here:
https://github.com/palasthotel/grid/commit/89d75e6b7d5a9dc43cdfbae334fb4a3b94bb4c52#diff-6cd667e196917d4746dec6260f0374ef

Rollout comes with next update of the grid plugin.

Thanks for the report!

**Comment by EdwardBock** [comment]
In addition:
You have a typo in your contentstructure arrays. Type is called contentstructure. All lowercase!
