### ISSUE TITLE
prepending and appending wrapping custom html to containers

### ISSUE THREAD

**Issue by barooney** [palasthotel/grid-wordpress#58]
It would be awesome to put HTML code in the prologs and epilogs, removing the ```.grid-container-before``` and ```.grid-container-after``` container.

**Comment by EdwardBock** [comment]
Prolog and Epilog are WYSIWYG fields. If you need plain HTML use a special box. You can remove the .grid-conatiner-befor and after by overwriting the grid container template. Won't fix.
