### ISSUE TITLE
Editor Widget Filter Bug

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#59]
We got an report for a problem when you add a new editor widget.

Worksnt:
```
$widgets['js'][] = ...
```
Works:
```
$widgets['js']['widget_name'] = ...
```
Tell me why?

**Comment by barooney** [comment]
The problem lays in here:

https://github.com/palasthotel/grid-wordpress/blob/master/wordpress_plugin.php#L933

```
foreach ( $js as $idx => $file ) {
	wp_enqueue_script( 'grid_js_'.$idx, plugins_url( 'lib/'.$file, __FILE__ ) );
}
foreach ( $editor_widgets["js"] as $key => $url ) {
	wp_enqueue_script( 'grid_js_'.$key, $url );
}
```

Having both indices with auto-incremented values will result in two scripts tagged ```grid_js_0```, ```grid_js_1``` and so on.

Changing one of the two prefixes should solve the problem. You should think of dependencies across  the scripts, though.

**Comment by EdwardBock** [comment]
@barooney 
Thanks for the report. Fixed that problem by using an different key prefix for lib js files.
