### ISSUE TITLE
Wiederverwendbarer Container lässt sich nicht bearbeiten

### ISSUE THREAD

**Issue by benthebear** [palasthotel/grid-wordpress#63]
http://owl-dev.palasthotel.de/wordpress/wp-admin/admin.php?page=grid_edit_reuse_container&containerid=0
![bildschirmfoto 2015-09-09 um 16 54 26](https://cloud.githubusercontent.com/assets/49137/9765257/a27909c0-5713-11e5-9a0f-49fce83fd6fe.png)

**Comment by EdwardBock** [comment]
Done
