### ISSUE TITLE
128 Vulnerabilities?

### ISSUE THREAD

**Issue by kroppenstedt** [palasthotel/grid-wordpress#66]
@mkernel und @EdwardBock 
http://php-grinder.com/project/view/17125
![screenshot 2016-01-07 09 17 02](https://cloud.githubusercontent.com/assets/4907934/12165589/7d5422c8-b51f-11e5-8d4e-a3112cb9b3a8.png)

**Comment by mkernel** [comment]
I'll have a look. It's obviously only one vulnerability as it's only one location in code.

**Comment by mkernel** [comment]
fixed in https://github.com/palasthotel/grid/commit/df976e6c00f5963ca5a1096cb9ea667f0b0e8233

@EdwardBock please release a grid update for wordpress.

**Comment by mkernel** [comment]
(oh and please double check my changes!)

**Comment by EdwardBock** [comment]
@mkernel looks good now. Release is to be released ;)

**Comment by EdwardBock** [comment]
Ups lets have a look again here: http://php-grinder.com/project/view/17125

**Comment by EdwardBock** [comment]
Queued for next test:
http://php-grinder.com/project/view/39344

**Comment by EdwardBock** [comment]
Nothing found. Good job. Thanks @mkernel for fixing and @kroppenstedt for reporting!
