### ISSUE TITLE
Can't select PDF form Media

### ISSUE THREAD

**Issue by MarcusAbel** [palasthotel/grid-wordpress#67]
When you want to select Media, you are damned to choose Images right now.
Some documents would be nice ...

**Comment by EdwardBock** [comment]
You can either select what you want to have in the media-box in the grid options now or build a custom grid box with the media select widget and use the new media_type option in the content structure to allow more than just images.
Release 1.5.9

**Comment by MarcusAbel** [comment]
Thanks
