### ISSUE TITLE
Path with double slashes

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid-wordpress#68]
There is [this line](https://github.com/palasthotel/grid-wordpress/blob/master/core/templates/wordpress/grid-box-posts.tpl.php#L35):
```PHP
if ( file_exists( $this->storage->templatesPath.'/post_content.tpl.php' ) ) {
```
In my Debugger the templatePath ends with a slash, so we have a path with double slashes, which may lead to issues. I don't know if this is setup dependent, so we should use something like [trailingslashit()](https://codex.wordpress.org/Function_Reference/trailingslashit).

Same problem two lines below.

**Comment by mkernel** [comment]
I'm not aware of ANY operating system in the wild (especially server-side) which has problems with multiple path separators. That's not good, but won't break.

**Comment by EdwardBock** [comment]
@greatestview @mkernel 
No bug but for clean work reasons we use trailingslashit now :)
