### ISSUE TITLE
Deprecated function get_currentuserinfo

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#69]
We have to refactore because a function has been deprecated

https://codex.wordpress.org/Function_Reference/get_currentuserinfo

https://github.com/palasthotel/grid-wordpress/blob/7caa8f4e0be03779d8fddcf89c1378624c564d70/classes/the_grid.inc#L95

**Comment by EdwardBock** [comment]
@mkernel 
for you :)

**Comment by mkernel** [comment]
fixed - please publish an update.

**Comment by EdwardBock** [comment]
Thanks!
