### ISSUE TITLE
List Box teaser filter

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#72]
There are people ( @benthebear ) that would like to see a filter to add templates for teaser lists to the grid list box.

The default ca render except and full at the moment. A new filter called from the theme should override possible teaser templates like:

default array('excerpt','full')

from theme: array('teaser1','teaser2')

than the box would try to render a post with:

get_template_part('teaser1') or get_template_part('teaser2')

**Comment by benthebear** [comment]
Better would be a definition-list with a machine-readable name (for files), a short titel and a longer Descripttion, like this:

array( 
  array(
           slug => 'teaser',
           titel => 'Basic Teaser',
           description => 'Your should use this one as default'
  ),
 array(
           slug => 'list-teaser',
           titel => 'List Teaser',
           description => 'Your should use this one short lists, contains only the title.'
  ),
);

**Comment by EdwardBock** [comment]
@benthebear 
I've found a already implanted filter for that :D 

https://github.com/palasthotel/grid-wordpress/blob/master/core/classes/wordpress/grid_posts_box.php#L193-L199

So, done :) I already implemented it in the project with @kroppenstedt
