### ISSUE TITLE
Compatibility with Yoast

### ISSUE THREAD

**Issue by benthebear** [palasthotel/grid-wordpress#74]
@EdwardBock We need to check Compatibility with Yoast on request of @mneuss

**Comment by EdwardBock** [comment]
I will do so!

**Comment by EdwardBock** [comment]
I did install the yoast pugin. grid works perfectly!

we only had some problems in the past when we tried to ignore duplicates. We did that by filling out an global php array. but yoast does something like rendering the page / content twice so all placed post got ignored. But that has nothing to do with the grid core plugin.

**Comment by benthebear** [comment]
As far as I know @kroppenstedt ran into that problem just recently …

**Comment by EdwardBock** [comment]
@mkernel 

You had an idea for the avoid doubletts problem. Let's keep this ticket as a reminder to talk about it.

**Comment by EdwardBock** [comment]
Grid has a new hook mechanism now and we have a new plugin in line that handles the new way of doublets avoiding. I'll try that with yoast

**Comment by EdwardBock** [comment]
works!
