### ISSUE TITLE
Grid for taxonomy pages

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#76]
We want a solution for overriding the first page of a taxonomy page with grid.

**Comment by greatestview** [comment]
Idea from our chat: Include an option to define the offset für page 2, which defaults to 0. If you place a content by selection box on the page 1 grid, which shows the newest 10 tag related posts, you could set the offset for page two to 10, so that the next article on page 2 would be the 11th.

**Comment by benthebear** [comment]
Please consider building this a seperate Plugin with the following Features:

* For each term allow a Page (Conten Type) to be chosen, that overrides the first page of the Term
* Render the Page wether it's a grid or only a normal Page
* Keep the Pagination
* Make the Offset for PAge 2 Configurable

**Comment by benthebear** [comment]
@greatestview Ah. Hihi.

**Comment by JuliaKrischik** [comment]
This will not be a grid feature and we will develop this in a seperate plugin.
