### ISSUE TITLE
Planned Posts

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#87]
What's the best way to visualize planned posts for authors on grid pages?

My suggestion:

 - Planned posts will only be displayed on grid preview page
 - Planned posts are not displayed on published grid
 - Planned posts have a is-planned class for styling

Everything else has to be implemented in theme templates.

What do you think @palasthotel/developers ?

**Comment by greatestview** [comment]
Very difficult. It would be confusing to show a preview grid which is different from the published grid. They should have the same contents from my opinion. Also the published grid page should look the same regardless of being logged in or not (I think most customers check their homepage while being logged in).

I think the best and most intuitive way would be an opt-in setting to show planned posts, when logged in, regardless of being on a preview or published grid page.

And yes, an additional CSS-class should be applied for theming.

**Comment by EdwardBock** [comment]
Moved from Feature Request to Bugfix because it was a litte bug that was responsible for future posts in frontend.
