### ISSUE TITLE
Duplicate boxes within a grid

### ISSUE THREAD

**Issue by JuliaKrischik** [palasthotel/grid-wordpress#88]
Hi @EdwardBock,

sometimes I wish I could simply duplicate my grid-boxes, because often when I build a grid I need the same box several times and just need to change one single setting. It would be very nice if I had the possibility to duplicate a box and the duplicated box would then appear right under the original and I could then move it to its position and adjust it.

Can you build this feature?

**Comment by EdwardBock** [comment]
I think you are not the first one ;)

https://github.com/palasthotel/grid/issues/435

But YES. That's a planned feature.

**Comment by JuliaKrischik** [comment]
Ah, I didn't find this. So I will close here. Thanks:)
