### ISSUE TITLE
Need of Hook-Publish

### ISSUE THREAD

**Issue by benthebear** [palasthotel/grid-wordpress#94]
@EdwardBock A Customer need a Publish-Hook. Could you be so kind an build one for me. It should be fired everytime a Grid is published …

**Comment by EdwardBock** [comment]
There are several new hooks with release https://github.com/palasthotel/grid/releases/tag/v1.7.0

Have a look at the new documentation pages.

http://doc.the-grid.ws/dokumentation/entwickler/hooks/

http://doc.the-grid.ws/dokumentation/entwickler/wordpress-hooks/
