### ISSUE TITLE
Feature-Wunsch: Postqueues direkt im Grid bearbeiten

### ISSUE THREAD

**Issue by NicoASMB** [palasthotel/grid-wordpress#99]
Wenn ich im Grid bin und dort einen Container mit einer Postqueue sehe, wäre es doch cool, wenn es hier den Button „Postqueue bearbeiten“ geben würde, mit dem ich direkt zur Postqueue lande.

![bildschirmfoto 2018-03-02 um 17 27 55](https://user-images.githubusercontent.com/14998804/36909721-1e136324-1e3f-11e8-9429-bab2a1ec4835.png)

ENGLISH:

When I'm in the grid and see a container that contains a postqueue, it would be very convenient to have a button "Edit Postqueue“ that lets me directly jump to that particular postqueue.

**Comment by StefanBoettcherASMB** [comment]
oder einen Hook um Links einzuhooken...

**Comment by EdwardBock** [comment]
Thank's for the feedback but that's not a grid topic but an implementation detail of the postqueue grid box. But it's a good idea. I'll move this issue to postqueue repo.
